# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pio.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pio.proto',
  package='packets_io',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tpio.proto\x12\npackets_io\"6\n\x06packet\x12\x11\n\tsubifname\x18\x01 \x01(\t\x12\x0b\n\x03len\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\">\n\x0c\x62ulk_packets\x12\t\n\x01n\x18\x01 \x01(\x03\x12#\n\x07packets\x18\x02 \x03(\x0b\x32\x12.packets_io.packet\"\x13\n\x06result\x12\t\n\x01r\x18\x01 \x01(\x03\"\x06\n\x04null2\x84\x01\n\npackets_io\x12;\n\tsend_bulk\x12\x18.packets_io.bulk_packets\x1a\x12.packets_io.result\"\x00\x12\x39\n\trecv_bulk\x12\x10.packets_io.null\x1a\x18.packets_io.bulk_packets\"\x00\x62\x06proto3')
)




_PACKET = _descriptor.Descriptor(
  name='packet',
  full_name='packets_io.packet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subifname', full_name='packets_io.packet.subifname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='len', full_name='packets_io.packet.len', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='packets_io.packet.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=79,
)


_BULK_PACKETS = _descriptor.Descriptor(
  name='bulk_packets',
  full_name='packets_io.bulk_packets',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n', full_name='packets_io.bulk_packets.n', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packets', full_name='packets_io.bulk_packets.packets', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=143,
)


_RESULT = _descriptor.Descriptor(
  name='result',
  full_name='packets_io.result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='r', full_name='packets_io.result.r', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=164,
)


_NULL = _descriptor.Descriptor(
  name='null',
  full_name='packets_io.null',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=172,
)

_BULK_PACKETS.fields_by_name['packets'].message_type = _PACKET
DESCRIPTOR.message_types_by_name['packet'] = _PACKET
DESCRIPTOR.message_types_by_name['bulk_packets'] = _BULK_PACKETS
DESCRIPTOR.message_types_by_name['result'] = _RESULT
DESCRIPTOR.message_types_by_name['null'] = _NULL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

packet = _reflection.GeneratedProtocolMessageType('packet', (_message.Message,), dict(
  DESCRIPTOR = _PACKET,
  __module__ = 'pio_pb2'
  # @@protoc_insertion_point(class_scope:packets_io.packet)
  ))
_sym_db.RegisterMessage(packet)

bulk_packets = _reflection.GeneratedProtocolMessageType('bulk_packets', (_message.Message,), dict(
  DESCRIPTOR = _BULK_PACKETS,
  __module__ = 'pio_pb2'
  # @@protoc_insertion_point(class_scope:packets_io.bulk_packets)
  ))
_sym_db.RegisterMessage(bulk_packets)

result = _reflection.GeneratedProtocolMessageType('result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'pio_pb2'
  # @@protoc_insertion_point(class_scope:packets_io.result)
  ))
_sym_db.RegisterMessage(result)

null = _reflection.GeneratedProtocolMessageType('null', (_message.Message,), dict(
  DESCRIPTOR = _NULL,
  __module__ = 'pio_pb2'
  # @@protoc_insertion_point(class_scope:packets_io.null)
  ))
_sym_db.RegisterMessage(null)



_PACKETS_IO = _descriptor.ServiceDescriptor(
  name='packets_io',
  full_name='packets_io.packets_io',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=175,
  serialized_end=307,
  methods=[
  _descriptor.MethodDescriptor(
    name='send_bulk',
    full_name='packets_io.packets_io.send_bulk',
    index=0,
    containing_service=None,
    input_type=_BULK_PACKETS,
    output_type=_RESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='recv_bulk',
    full_name='packets_io.packets_io.recv_bulk',
    index=1,
    containing_service=None,
    input_type=_NULL,
    output_type=_BULK_PACKETS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PACKETS_IO)

DESCRIPTOR.services_by_name['packets_io'] = _PACKETS_IO

# @@protoc_insertion_point(module_scope)
