# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import pio_pb2 as pio__pb2


class packets_ioStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.send_bulk = channel.unary_unary(
        '/packets_io.packets_io/send_bulk',
        request_serializer=pio__pb2.bulk_packets.SerializeToString,
        response_deserializer=pio__pb2.result.FromString,
        )
    self.recv_bulk = channel.unary_unary(
        '/packets_io.packets_io/recv_bulk',
        request_serializer=pio__pb2.null.SerializeToString,
        response_deserializer=pio__pb2.bulk_packets.FromString,
        )


class packets_ioServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def send_bulk(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def recv_bulk(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_packets_ioServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'send_bulk': grpc.unary_unary_rpc_method_handler(
          servicer.send_bulk,
          request_deserializer=pio__pb2.bulk_packets.FromString,
          response_serializer=pio__pb2.result.SerializeToString,
      ),
      'recv_bulk': grpc.unary_unary_rpc_method_handler(
          servicer.recv_bulk,
          request_deserializer=pio__pb2.null.FromString,
          response_serializer=pio__pb2.bulk_packets.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'packets_io.packets_io', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
